spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/abc
    username: sa
    password:
    driver-class-name: org.h2.Driver
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: debug
      org.springframework.security: debug
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
        hibernate:
#            show_sql: true
            format_sql: true
            dialect: org.hibernate.dialect.H2Dialect
  security:
    debug: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jinwoo2328@gmail.com
    password: bthu bgqg rkeh urxb
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 600000
